import "dotenv/config";
import argon2 from "argon2";
import { prisma } from "../src/prisma.js";

async function upsertRows<T extends { id: string }>(
  model: {
    upsert: (args: { where: { id: string }; update: Omit<T, "id">; create: T }) => Promise<unknown>;
  },
  rows: T[],
) {
  for (const row of rows) {
    const { id, ...update } = row;
    await model.upsert({
      where: { id },
      update,
      create: row,
    });
  }
}

async function main() {
  const passwordHash = await argon2.hash("Password123!");
  const now = new Date();

  await upsertRows(prisma.user, [
      {
        id: "seed_user_admin",
        email: "admin@qlaim.dev",
        passwordHash,
        role: "ADMIN",
      },
      {
        id: "seed_user_owner_1",
        email: "owner1@qlaim.dev",
        passwordHash,
      },
      {
        id: "seed_user_manager_1",
        email: "manager1@qlaim.dev",
        passwordHash,
      },
      {
        id: "seed_user_creator_1",
        email: "creator1@qlaim.dev",
        passwordHash,
      },
      {
        id: "seed_user_owner_2",
        email: "owner2@qlaim.dev",
        passwordHash,
      },
      {
        id: "seed_user_worker_1",
        email: "worker1@qlaim.dev",
        passwordHash,
      },
      {
        id: "seed_user_worker_2",
        email: "worker2@qlaim.dev",
        passwordHash,
      },
      {
        id: "seed_user_worker_3",
        email: "worker3@qlaim.dev",
        passwordHash,
      },
    ]);

  await upsertRows(prisma.profile, [
      {
        id: "seed_profile_admin",
        userId: "seed_user_admin",
        firstName: "Alex",
        lastName: "Admin",
        username: "alex_admin",
        zipcode: "73102",
        tier: "DIAMOND",
        starsBalance: 1200,
        ratingAvg: 5.0,
        ratingCount: 44,
      },
      {
        id: "seed_profile_owner_1",
        userId: "seed_user_owner_1",
        firstName: "Olivia",
        lastName: "Owner",
        username: "olivia_owner",
        zipcode: "73112",
        tier: "PLATINUM",
        starsBalance: 800,
        ratingAvg: 4.9,
        ratingCount: 20,
      },
      {
        id: "seed_profile_manager_1",
        userId: "seed_user_manager_1",
        firstName: "Marco",
        lastName: "Manager",
        username: "marco_manager",
        zipcode: "73099",
        tier: "GOLD",
        starsBalance: 600,
        ratingAvg: 4.8,
        ratingCount: 18,
      },
      {
        id: "seed_profile_creator_1",
        userId: "seed_user_creator_1",
        firstName: "Casey",
        lastName: "Creator",
        username: "casey_creator",
        zipcode: "73120",
        tier: "SILVER",
        starsBalance: 430,
        ratingAvg: 4.7,
        ratingCount: 13,
      },
      {
        id: "seed_profile_owner_2",
        userId: "seed_user_owner_2",
        firstName: "Parker",
        lastName: "Owner",
        username: "parker_owner",
        zipcode: "74133",
        tier: "PLATINUM",
        starsBalance: 910,
        ratingAvg: 4.95,
        ratingCount: 29,
      },
      {
        id: "seed_profile_worker_1",
        userId: "seed_user_worker_1",
        firstName: "Wes",
        lastName: "Worker",
        username: "wes_worker",
        zipcode: "74104",
        tier: "BRONZE",
        starsBalance: 220,
        ratingAvg: 4.5,
        ratingCount: 9,
      },
      {
        id: "seed_profile_worker_2",
        userId: "seed_user_worker_2",
        firstName: "Riley",
        lastName: "Worker",
        username: "riley_worker",
        zipcode: "74136",
        tier: "SILVER",
        starsBalance: 340,
        ratingAvg: 4.6,
        ratingCount: 11,
      },
      {
        id: "seed_profile_worker_3",
        userId: "seed_user_worker_3",
        firstName: "Jordan",
        lastName: "Worker",
        username: "jordan_worker",
        zipcode: "74137",
        tier: "GOLD",
        starsBalance: 500,
        ratingAvg: 4.85,
        ratingCount: 15,
      },
    ]);

  await upsertRows(prisma.refreshToken, [
      {
        id: "seed_refresh_1",
        userId: "seed_user_owner_1",
        tokenHash: "seed_refresh_token_hash_1",
        expiresAt: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000),
      },
      {
        id: "seed_refresh_2",
        userId: "seed_user_worker_1",
        tokenHash: "seed_refresh_token_hash_2",
        expiresAt: new Date(now.getTime() + 12 * 24 * 60 * 60 * 1000),
      },
      {
        id: "seed_refresh_3",
        userId: "seed_user_worker_2",
        tokenHash: "seed_refresh_token_hash_3",
        expiresAt: new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000),
      },
      {
        id: "seed_refresh_4",
        userId: "seed_user_admin",
        tokenHash: "seed_refresh_token_hash_4",
        expiresAt: new Date(now.getTime() + 20 * 24 * 60 * 60 * 1000),
      },
    ]);

  await upsertRows(prisma.passwordResetToken, [
      {
        id: "seed_reset_1",
        userId: "seed_user_owner_1",
        tokenHash: "seed_password_reset_hash_1",
        expiresAt: new Date(now.getTime() + 60 * 60 * 1000),
      },
      {
        id: "seed_reset_2",
        userId: "seed_user_worker_1",
        tokenHash: "seed_password_reset_hash_2",
        expiresAt: new Date(now.getTime() + 2 * 60 * 60 * 1000),
      },
      {
        id: "seed_reset_3",
        userId: "seed_user_worker_2",
        tokenHash: "seed_password_reset_hash_3",
        expiresAt: new Date(now.getTime() + 3 * 60 * 60 * 1000),
      },
      {
        id: "seed_reset_4",
        userId: "seed_user_admin",
        tokenHash: "seed_password_reset_hash_4",
        expiresAt: new Date(now.getTime() + 4 * 60 * 60 * 1000),
        usedAt: new Date(now.getTime() - 15 * 60 * 1000),
      },
    ]);

  await upsertRows(prisma.company, [
      { id: "seed_company_1", name: "Northstar Logistics" },
      { id: "seed_company_2", name: "Bright Bean Coffee" },
      { id: "seed_company_3", name: "Apex Home Services" },
      { id: "seed_company_4", name: "River City Events" },
    ]);

  await upsertRows(prisma.location, [
      {
        id: "seed_location_1",
        name: "North Depot",
        address: "1201 N Walker Ave",
        city: "Oklahoma City",
        state: "OK",
        zipcode: "73103",
        lat: 35.4804,
        lng: -97.5183,
      },
      {
        id: "seed_location_2",
        name: "Downtown Kiosk",
        address: "333 W Sheridan Ave",
        city: "Oklahoma City",
        state: "OK",
        zipcode: "73102",
        lat: 35.4677,
        lng: -97.5206,
      },
      {
        id: "seed_location_3",
        name: "Tulsa Midtown Hub",
        address: "4502 E 31st St",
        city: "Tulsa",
        state: "OK",
        zipcode: "74135",
        lat: 36.1188,
        lng: -95.9292,
      },
      {
        id: "seed_location_4",
        name: "Riverside Office",
        address: "600 S Boulder Ave",
        city: "Tulsa",
        state: "OK",
        zipcode: "74119",
        lat: 36.1517,
        lng: -95.9892,
      },
    ]);

  await upsertRows(prisma.member, [
      {
        id: "seed_member_1",
        companyId: "seed_company_1",
        userId: "seed_user_owner_1",
        role: "OWNER",
      },
      {
        id: "seed_member_2",
        companyId: "seed_company_1",
        userId: "seed_user_manager_1",
        role: "MANAGER",
      },
      {
        id: "seed_member_3",
        companyId: "seed_company_1",
        userId: "seed_user_creator_1",
        role: "CREATOR",
      },
      {
        id: "seed_member_4",
        companyId: "seed_company_1",
        userId: "seed_user_admin",
        role: "APPROVER",
      },
      {
        id: "seed_member_5",
        companyId: "seed_company_2",
        userId: "seed_user_owner_2",
        role: "OWNER",
      },
      {
        id: "seed_member_6",
        companyId: "seed_company_2",
        userId: "seed_user_admin",
        role: "MANAGER",
      },
      {
        id: "seed_member_7",
        companyId: "seed_company_2",
        userId: "seed_user_worker_3",
        role: "CREATOR",
      },
      {
        id: "seed_member_8",
        companyId: "seed_company_3",
        userId: "seed_user_admin",
        role: "OWNER",
      },
      {
        id: "seed_member_9",
        companyId: "seed_company_3",
        userId: "seed_user_worker_2",
        role: "MANAGER",
      },
      {
        id: "seed_member_10",
        companyId: "seed_company_3",
        userId: "seed_user_worker_1",
        role: "CREATOR",
      },
      {
        id: "seed_member_11",
        companyId: "seed_company_4",
        userId: "seed_user_owner_2",
        role: "OWNER",
      },
      {
        id: "seed_member_12",
        companyId: "seed_company_4",
        userId: "seed_user_manager_1",
        role: "APPROVER",
      },
    ]);

  await upsertRows(prisma.companyMembershipRequest, [
      {
        id: "seed_request_1",
        companyId: "seed_company_1",
        userId: "seed_user_worker_2",
        requestedRole: "APPROVER",
        note: "Have dispatch and quality audit background.",
        status: "DENIED",
        resolvedByUserId: "seed_user_owner_1",
        resolvedNote: "No open approver position at this time.",
        resolvedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000),
      },
      {
        id: "seed_request_2",
        companyId: "seed_company_2",
        userId: "seed_user_worker_1",
        requestedRole: "CREATOR",
        note: "Can cover delivery and storefront audits.",
        status: "APPROVED",
        resolvedByUserId: "seed_user_admin",
        resolvedNote: "Approved for trial period.",
        resolvedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        id: "seed_request_3",
        companyId: "seed_company_3",
        userId: "seed_user_owner_2",
        requestedRole: "MANAGER",
        note: "Interested in helping with scheduling.",
        status: "PENDING",
      },
      {
        id: "seed_request_4",
        companyId: "seed_company_4",
        userId: "seed_user_worker_3",
        requestedRole: "APPROVER",
        note: "Available nights and weekends for reviews.",
        status: "PENDING",
      },
    ]);

  await upsertRows(prisma.gig, [
      {
        id: "seed_gig_1",
        companyId: "seed_company_1",
        createdByUserId: "seed_user_creator_1",
        title: "Install New Shelf Labels",
        description: "Update pricing labels for aisle 3 and 4.",
        type: "STANDARD",
        locationId: "seed_location_1",
        startsAt: new Date(now.getTime() + 3 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 7 * 60 * 60 * 1000),
        payCents: 6500,
        units: 1,
        basePriceCents: 6500,
        bumpEverySeconds: 1800,
        bumpCents: 150,
        maxBumps: 4,
        maxPriceCents: 7100,
        baseStars: 8,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 3,
        repostBonusPerRepost: 1,
        requiredTier: "BRONZE",
        repostCount: 0,
        escalationCount: 0,
        status: "OPEN",
      },
      {
        id: "seed_gig_2",
        companyId: "seed_company_1",
        createdByUserId: "seed_user_owner_1",
        title: "Inventory Cycle Count",
        description: "Count and verify all premium inventory bins.",
        type: "AUDIT",
        locationId: "seed_location_2",
        startsAt: new Date(now.getTime() - 9 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() - 6 * 60 * 60 * 1000),
        payCents: 9200,
        units: 1,
        basePriceCents: 9200,
        bumpEverySeconds: 1200,
        bumpCents: 200,
        maxBumps: 5,
        maxPriceCents: 10200,
        baseStars: 12,
        starsBumpEverySeconds: 1200,
        starsBumpAmount: 1,
        maxAgeBonusStars: 4,
        repostBonusPerRepost: 1,
        requiredTier: "SILVER",
        repostCount: 1,
        escalationCount: 1,
        lastEscalatedAt: new Date(now.getTime() - 10 * 60 * 60 * 1000),
        status: "COMPLETED",
      },
      {
        id: "seed_gig_3",
        companyId: "seed_company_2",
        createdByUserId: "seed_user_owner_2",
        title: "Morning Delivery Run",
        description: "Deliver product kits to three downtown offices.",
        type: "DELIVERY",
        locationId: "seed_location_3",
        startsAt: new Date(now.getTime() - 13 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
        payCents: 11500,
        units: 1,
        basePriceCents: 11500,
        bumpEverySeconds: 1800,
        bumpCents: 250,
        maxBumps: 3,
        maxPriceCents: 12250,
        baseStars: 14,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 2,
        repostBonusPerRepost: 2,
        requiredTier: "SILVER",
        repostCount: 1,
        escalationCount: 2,
        lastEscalatedAt: new Date(now.getTime() - 12 * 60 * 60 * 1000),
        status: "COMPLETED",
      },
      {
        id: "seed_gig_4",
        companyId: "seed_company_3",
        createdByUserId: "seed_user_admin",
        title: "Post-Repair Safety Audit",
        description: "Capture photos and checklist for four units.",
        type: "AUDIT",
        locationId: "seed_location_4",
        startsAt: new Date(now.getTime() - 18 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() - 13 * 60 * 60 * 1000),
        payCents: 13200,
        units: 1,
        basePriceCents: 13200,
        bumpEverySeconds: 900,
        bumpCents: 300,
        maxBumps: 4,
        maxPriceCents: 14400,
        baseStars: 16,
        starsBumpEverySeconds: 900,
        starsBumpAmount: 1,
        maxAgeBonusStars: 4,
        repostBonusPerRepost: 2,
        requiredTier: "GOLD",
        repostCount: 2,
        escalationCount: 1,
        lastEscalatedAt: new Date(now.getTime() - 16 * 60 * 60 * 1000),
        status: "COMPLETED",
      },
      {
        id: "seed_gig_5",
        companyId: "seed_company_4",
        createdByUserId: "seed_user_owner_2",
        title: "Vendor Booth Setup",
        description: "Assemble tents and signage before event open.",
        type: "STANDARD",
        locationId: "seed_location_3",
        startsAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 2 * 60 * 60 * 1000),
        payCents: 8700,
        units: 1,
        basePriceCents: 8700,
        bumpEverySeconds: 1800,
        bumpCents: 125,
        maxBumps: 6,
        maxPriceCents: 9450,
        baseStars: 10,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 5,
        repostBonusPerRepost: 1,
        requiredTier: "BRONZE",
        repostCount: 0,
        escalationCount: 0,
        status: "IN_PROGRESS",
      },
      {
        id: "seed_gig_6",
        companyId: "seed_company_2",
        createdByUserId: "seed_user_worker_3",
        title: "Menu Board Refresh",
        description: "Replace menu board art and clean frame edges.",
        type: "STANDARD",
        locationId: "seed_location_2",
        startsAt: new Date(now.getTime() + 24 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 27 * 60 * 60 * 1000),
        payCents: 5400,
        units: 1,
        basePriceCents: 5400,
        bumpEverySeconds: 1800,
        bumpCents: 100,
        maxBumps: 5,
        maxPriceCents: 5900,
        baseStars: 6,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 3,
        repostBonusPerRepost: 1,
        requiredTier: "COPPER",
        repostCount: 0,
        escalationCount: 0,
        status: "DRAFT",
      },
      {
        id: "seed_gig_7",
        companyId: "seed_company_1",
        createdByUserId: "seed_user_manager_1",
        title: "Dock Receiving Photo Audit",
        description: "Capture and upload condition photos for inbound pallets.",
        type: "AUDIT",
        locationId: "seed_location_1",
        startsAt: new Date(now.getTime() + 90 * 60 * 1000),
        endsAt: new Date(now.getTime() + 4 * 60 * 60 * 1000),
        payCents: 7400,
        units: 1,
        basePriceCents: 7400,
        bumpEverySeconds: 1200,
        bumpCents: 175,
        maxBumps: 4,
        maxPriceCents: 8100,
        baseStars: 9,
        starsBumpEverySeconds: 1200,
        starsBumpAmount: 1,
        maxAgeBonusStars: 4,
        repostBonusPerRepost: 1,
        requiredTier: "COPPER",
        repostCount: 1,
        escalationCount: 1,
        lastEscalatedAt: new Date(now.getTime() - 30 * 60 * 1000),
        status: "OPEN",
      },
      {
        id: "seed_gig_8",
        companyId: "seed_company_2",
        createdByUserId: "seed_user_owner_2",
        title: "Afternoon Catering Drop",
        description: "Deliver boxed lunches to two office towers.",
        type: "DELIVERY",
        locationId: "seed_location_3",
        startsAt: new Date(now.getTime() + 5 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 8 * 60 * 60 * 1000),
        payCents: 9800,
        units: 1,
        basePriceCents: 9800,
        bumpEverySeconds: 1800,
        bumpCents: 200,
        maxBumps: 5,
        maxPriceCents: 10800,
        baseStars: 11,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 3,
        repostBonusPerRepost: 2,
        requiredTier: "BRONZE",
        repostCount: 0,
        escalationCount: 0,
        status: "OPEN",
      },
      {
        id: "seed_gig_9",
        companyId: "seed_company_3",
        createdByUserId: "seed_user_worker_2",
        title: "HVAC Filter Replacement Check",
        description: "Confirm filter swap completion in six units.",
        type: "STANDARD",
        locationId: "seed_location_4",
        startsAt: new Date(now.getTime() + 10 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 15 * 60 * 60 * 1000),
        payCents: 12500,
        units: 1,
        basePriceCents: 12500,
        bumpEverySeconds: 900,
        bumpCents: 250,
        maxBumps: 6,
        maxPriceCents: 14000,
        baseStars: 15,
        starsBumpEverySeconds: 900,
        starsBumpAmount: 1,
        maxAgeBonusStars: 5,
        repostBonusPerRepost: 2,
        requiredTier: "GOLD",
        repostCount: 2,
        escalationCount: 2,
        lastEscalatedAt: new Date(now.getTime() - 75 * 60 * 1000),
        status: "OPEN",
      },
      {
        id: "seed_gig_10",
        companyId: "seed_company_4",
        createdByUserId: "seed_user_owner_2",
        title: "Late Night Breakdown Crew",
        description: "Disassemble event booths after close and stage for pickup.",
        type: "STANDARD",
        locationId: "seed_location_3",
        startsAt: new Date(now.getTime() + 12 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 17 * 60 * 60 * 1000),
        payCents: 14900,
        units: 1,
        basePriceCents: 14900,
        bumpEverySeconds: 900,
        bumpCents: 300,
        maxBumps: 5,
        maxPriceCents: 16400,
        baseStars: 18,
        starsBumpEverySeconds: 900,
        starsBumpAmount: 2,
        maxAgeBonusStars: 6,
        repostBonusPerRepost: 2,
        requiredTier: "PLATINUM",
        repostCount: 1,
        escalationCount: 1,
        lastEscalatedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
        status: "OPEN",
      },
      {
        id: "seed_gig_11",
        companyId: "seed_company_2",
        createdByUserId: "seed_user_admin",
        title: "Drive-Thru Line Timing Study",
        description: "Measure and report throughput during lunch peak.",
        type: "AUDIT",
        locationId: "seed_location_2",
        startsAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
        payCents: 6100,
        units: 1,
        basePriceCents: 6100,
        bumpEverySeconds: 1800,
        bumpCents: 100,
        maxBumps: 3,
        maxPriceCents: 6400,
        baseStars: 7,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 2,
        repostBonusPerRepost: 1,
        requiredTier: "COPPER",
        repostCount: 0,
        escalationCount: 0,
        status: "CANCELLED",
      },
      {
        id: "seed_gig_12",
        companyId: "seed_company_1",
        createdByUserId: "seed_user_creator_1",
        title: "Weekend Shelf Reset",
        description: "Reset endcaps per merchandising planogram.",
        type: "STANDARD",
        locationId: "seed_location_1",
        startsAt: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000),
        payCents: 7800,
        units: 1,
        basePriceCents: 7800,
        bumpEverySeconds: 1800,
        bumpCents: 120,
        maxBumps: 4,
        maxPriceCents: 8280,
        baseStars: 9,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 3,
        repostBonusPerRepost: 1,
        requiredTier: "BRONZE",
        repostCount: 0,
        escalationCount: 0,
        status: "OPEN",
      },
      {
        id: "seed_gig_13",
        companyId: "seed_company_3",
        createdByUserId: "seed_user_worker_1",
        title: "Emergency Water Leak Inspection",
        description: "Document leak source and update immediate hazard log.",
        type: "AUDIT",
        locationId: "seed_location_4",
        startsAt: new Date(now.getTime() + 20 * 60 * 1000),
        endsAt: new Date(now.getTime() + 2 * 60 * 60 * 1000),
        payCents: 15800,
        units: 1,
        basePriceCents: 15800,
        bumpEverySeconds: 600,
        bumpCents: 300,
        maxBumps: 6,
        maxPriceCents: 17600,
        baseStars: 20,
        starsBumpEverySeconds: 600,
        starsBumpAmount: 2,
        maxAgeBonusStars: 8,
        repostBonusPerRepost: 2,
        requiredTier: "DIAMOND",
        repostCount: 2,
        escalationCount: 3,
        lastEscalatedAt: new Date(now.getTime() - 15 * 60 * 1000),
        status: "OPEN",
      },
      {
        id: "seed_gig_14",
        companyId: "seed_company_4",
        createdByUserId: "seed_user_manager_1",
        title: "Ticket Scanner Calibration",
        description: "Run calibration pass on all gate scanners.",
        type: "STANDARD",
        locationId: "seed_location_3",
        startsAt: new Date(now.getTime() + 36 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 40 * 60 * 60 * 1000),
        payCents: 6900,
        units: 1,
        basePriceCents: 6900,
        bumpEverySeconds: 1800,
        bumpCents: 100,
        maxBumps: 5,
        maxPriceCents: 7400,
        baseStars: 8,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 3,
        repostBonusPerRepost: 1,
        requiredTier: "COPPER",
        repostCount: 0,
        escalationCount: 0,
        status: "DRAFT",
      },
      {
        id: "seed_gig_15",
        companyId: "seed_company_2",
        createdByUserId: "seed_user_worker_3",
        title: "Cold Brew Batch Transfer",
        description: "Move completed batches to bottling tank and sanitize lines.",
        type: "STANDARD",
        locationId: "seed_location_2",
        startsAt: new Date(now.getTime() + 7 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 10 * 60 * 60 * 1000),
        payCents: 8300,
        units: 1,
        basePriceCents: 8300,
        bumpEverySeconds: 1800,
        bumpCents: 140,
        maxBumps: 4,
        maxPriceCents: 8860,
        baseStars: 10,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 3,
        repostBonusPerRepost: 1,
        requiredTier: "SILVER",
        repostCount: 1,
        escalationCount: 1,
        lastEscalatedAt: new Date(now.getTime() - 3 * 60 * 60 * 1000),
        status: "OPEN",
      },
      {
        id: "seed_gig_16",
        companyId: "seed_company_1",
        createdByUserId: "seed_user_owner_1",
        title: "Forklift Battery Swap",
        description: "Replace batteries and record voltage checks.",
        type: "STANDARD",
        locationId: "seed_location_1",
        startsAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 60 * 60 * 1000),
        payCents: 10100,
        units: 1,
        basePriceCents: 10100,
        bumpEverySeconds: 1200,
        bumpCents: 180,
        maxBumps: 5,
        maxPriceCents: 11000,
        baseStars: 12,
        starsBumpEverySeconds: 1200,
        starsBumpAmount: 1,
        maxAgeBonusStars: 4,
        repostBonusPerRepost: 1,
        requiredTier: "BRONZE",
        repostCount: 1,
        escalationCount: 1,
        lastEscalatedAt: new Date(now.getTime() - 90 * 60 * 1000),
        status: "OPEN",
      },
      {
        id: "seed_gig_17",
        companyId: "seed_company_3",
        createdByUserId: "seed_user_admin",
        title: "Tenant Welcome Kit Delivery",
        description: "Deliver and log welcome packets for new move-ins.",
        type: "DELIVERY",
        locationId: "seed_location_4",
        startsAt: new Date(now.getTime() + 26 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 31 * 60 * 60 * 1000),
        payCents: 7200,
        units: 1,
        basePriceCents: 7200,
        bumpEverySeconds: 1800,
        bumpCents: 110,
        maxBumps: 5,
        maxPriceCents: 7750,
        baseStars: 8,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 3,
        repostBonusPerRepost: 1,
        requiredTier: "COPPER",
        repostCount: 0,
        escalationCount: 0,
        status: "OPEN",
      },
      {
        id: "seed_gig_18",
        companyId: "seed_company_4",
        createdByUserId: "seed_user_owner_2",
        title: "Stage Lighting Preflight",
        description: "Test lighting presets and document failed fixtures.",
        type: "AUDIT",
        locationId: "seed_location_3",
        startsAt: new Date(now.getTime() + 14 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 18 * 60 * 60 * 1000),
        payCents: 11800,
        units: 1,
        basePriceCents: 11800,
        bumpEverySeconds: 900,
        bumpCents: 220,
        maxBumps: 6,
        maxPriceCents: 13120,
        baseStars: 14,
        starsBumpEverySeconds: 900,
        starsBumpAmount: 1,
        maxAgeBonusStars: 5,
        repostBonusPerRepost: 2,
        requiredTier: "GOLD",
        repostCount: 1,
        escalationCount: 2,
        lastEscalatedAt: new Date(now.getTime() - 60 * 60 * 1000),
        status: "OPEN",
      },
      {
        id: "seed_gig_19",
        companyId: "seed_company_3",
        createdByUserId: "seed_user_worker_2",
        title: "Emergency Generator Load Test",
        description: "Run full-cycle backup generator load test and submit readings.",
        type: "AUDIT",
        locationId: "seed_location_4",
        startsAt: new Date(now.getTime() + 4 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 9 * 60 * 60 * 1000),
        payCents: 19500,
        units: 1,
        basePriceCents: 19500,
        bumpEverySeconds: 900,
        bumpCents: 300,
        maxBumps: 5,
        maxPriceCents: 21000,
        baseStars: 22,
        starsBumpEverySeconds: 900,
        starsBumpAmount: 2,
        maxAgeBonusStars: 6,
        repostBonusPerRepost: 2,
        requiredTier: "SILVER",
        repostCount: 1,
        escalationCount: 2,
        lastEscalatedAt: new Date(now.getTime() - 45 * 60 * 1000),
        status: "OPEN",
      },
      {
        id: "seed_gig_20",
        companyId: "seed_company_2",
        createdByUserId: "seed_user_worker_3",
        title: "Quick Cooler Temperature Check",
        description: "Log cooler temps at open and attach one verification photo.",
        type: "AUDIT",
        locationId: "seed_location_2",
        startsAt: new Date(now.getTime() + 75 * 60 * 1000),
        endsAt: new Date(now.getTime() + 3 * 60 * 60 * 1000),
        payCents: 4200,
        units: 1,
        basePriceCents: 4200,
        bumpEverySeconds: 1800,
        bumpCents: 75,
        maxBumps: 4,
        maxPriceCents: 4500,
        baseStars: 5,
        starsBumpEverySeconds: 1800,
        starsBumpAmount: 1,
        maxAgeBonusStars: 2,
        repostBonusPerRepost: 1,
        requiredTier: "COPPER",
        repostCount: 0,
        escalationCount: 0,
        status: "OPEN",
      },
      {
        id: "seed_gig_21",
        companyId: "seed_company_4",
        createdByUserId: "seed_user_owner_2",
        title: "Premium Rigging Final Inspection",
        description: "Inspect overhead rigging points and certify event readiness.",
        type: "AUDIT",
        locationId: "seed_location_3",
        startsAt: new Date(now.getTime() + 18 * 60 * 60 * 1000),
        endsAt: new Date(now.getTime() + 23 * 60 * 60 * 1000),
        payCents: 29900,
        units: 1,
        basePriceCents: 29900,
        bumpEverySeconds: 900,
        bumpCents: 400,
        maxBumps: 4,
        maxPriceCents: 31500,
        baseStars: 28,
        starsBumpEverySeconds: 900,
        starsBumpAmount: 2,
        maxAgeBonusStars: 6,
        repostBonusPerRepost: 2,
        requiredTier: "GOLD",
        repostCount: 1,
        escalationCount: 1,
        lastEscalatedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
        status: "OPEN",
      },
    ]);

  await upsertRows(prisma.watchlist, [
      {
        id: "seed_watchlist_1",
        userId: "seed_user_worker_1",
        gigId: "seed_gig_1",
      },
      {
        id: "seed_watchlist_2",
        userId: "seed_user_worker_2",
        gigId: "seed_gig_1",
      },
      {
        id: "seed_watchlist_3",
        userId: "seed_user_worker_3",
        gigId: "seed_gig_6",
      },
      {
        id: "seed_watchlist_4",
        userId: "seed_user_creator_1",
        gigId: "seed_gig_5",
      },
      {
        id: "seed_watchlist_5",
        userId: "seed_user_worker_1",
        gigId: "seed_gig_7",
      },
      {
        id: "seed_watchlist_6",
        userId: "seed_user_worker_2",
        gigId: "seed_gig_8",
      },
      {
        id: "seed_watchlist_7",
        userId: "seed_user_worker_3",
        gigId: "seed_gig_12",
      },
      {
        id: "seed_watchlist_8",
        userId: "seed_user_worker_2",
        gigId: "seed_gig_13",
      },
      {
        id: "seed_watchlist_9",
        userId: "seed_user_creator_1",
        gigId: "seed_gig_16",
      },
      {
        id: "seed_watchlist_10",
        userId: "seed_user_worker_1",
        gigId: "seed_gig_18",
      },
      {
        id: "seed_watchlist_11",
        userId: "seed_user_manager_1",
        gigId: "seed_gig_8",
      },
      {
        id: "seed_watchlist_12",
        userId: "seed_user_owner_1",
        gigId: "seed_gig_8",
      },
      {
        id: "seed_watchlist_13",
        userId: "seed_user_admin",
        gigId: "seed_gig_16",
      },
      {
        id: "seed_watchlist_14",
        userId: "seed_user_owner_2",
        gigId: "seed_gig_16",
      },
      {
        id: "seed_watchlist_15",
        userId: "seed_user_worker_3",
        gigId: "seed_gig_16",
      },
      {
        id: "seed_watchlist_16",
        userId: "seed_user_worker_1",
        gigId: "seed_gig_20",
      },
      {
        id: "seed_watchlist_17",
        userId: "seed_user_worker_2",
        gigId: "seed_gig_20",
      },
      {
        id: "seed_watchlist_18",
        userId: "seed_user_creator_1",
        gigId: "seed_gig_20",
      },
    ]);

  await upsertRows(prisma.gigAssignment, [
      {
        id: "seed_assignment_1",
        gigId: "seed_gig_2",
        userId: "seed_user_worker_1",
        status: "COMPLETED",
        note: "Completed count and uploaded final sheet.",
        assignedAt: new Date(now.getTime() - 9 * 60 * 60 * 1000),
        claimedAt: new Date(now.getTime() - 9 * 60 * 60 * 1000),
        startedAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
        submittedAt: new Date(now.getTime() - 7 * 60 * 60 * 1000),
        reviewedAt: new Date(now.getTime() - 6 * 60 * 60 * 1000),
        acceptedAt: new Date(now.getTime() - 6 * 60 * 60 * 1000),
        completedAt: new Date(now.getTime() - 6 * 60 * 60 * 1000),
      },
      {
        id: "seed_assignment_2",
        gigId: "seed_gig_3",
        userId: "seed_user_worker_2",
        status: "COMPLETED",
        note: "Delivered all kits and captured proof photos.",
        assignedAt: new Date(now.getTime() - 13 * 60 * 60 * 1000),
        claimedAt: new Date(now.getTime() - 13 * 60 * 60 * 1000),
        startedAt: new Date(now.getTime() - 12 * 60 * 60 * 1000),
        submittedAt: new Date(now.getTime() - 10 * 60 * 60 * 1000),
        reviewedAt: new Date(now.getTime() - 9 * 60 * 60 * 1000),
        acceptedAt: new Date(now.getTime() - 9 * 60 * 60 * 1000),
        completedAt: new Date(now.getTime() - 9 * 60 * 60 * 1000),
      },
      {
        id: "seed_assignment_3",
        gigId: "seed_gig_4",
        userId: "seed_user_worker_3",
        status: "COMPLETED",
        note: "Audit submitted with all required media.",
        assignedAt: new Date(now.getTime() - 18 * 60 * 60 * 1000),
        claimedAt: new Date(now.getTime() - 18 * 60 * 60 * 1000),
        startedAt: new Date(now.getTime() - 17 * 60 * 60 * 1000),
        submittedAt: new Date(now.getTime() - 15 * 60 * 60 * 1000),
        reviewedAt: new Date(now.getTime() - 14 * 60 * 60 * 1000),
        acceptedAt: new Date(now.getTime() - 14 * 60 * 60 * 1000),
        completedAt: new Date(now.getTime() - 14 * 60 * 60 * 1000),
      },
      {
        id: "seed_assignment_4",
        gigId: "seed_gig_5",
        userId: "seed_user_worker_1",
        status: "REVIEWED",
        note: "Setup done but missing one signage photo.",
        assignedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
        claimedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
        startedAt: new Date(now.getTime() - 90 * 60 * 1000),
        submittedAt: new Date(now.getTime() - 45 * 60 * 1000),
        reviewedAt: new Date(now.getTime() - 30 * 60 * 1000),
      },
    ]);

  await upsertRows(prisma.product, [
      {
        id: "seed_product_1",
        category: "MEMBERSHIP_UPGRADE",
        tier: "SILVER",
        title: "Tier Boost: Silver",
        subtitle: "Unlock silver-only opportunities for 30 days.",
        starsCost: 100,
        durationSeconds: 30 * 24 * 60 * 60,
      },
      {
        id: "seed_product_2",
        category: "MEMBERSHIP_UPGRADE",
        tier: "GOLD",
        title: "Tier Boost: Gold",
        subtitle: "Priority access to high-value gigs.",
        starsCost: 220,
        durationSeconds: 30 * 24 * 60 * 60,
      },
      {
        id: "seed_product_3",
        category: "PAY_BONUS",
        title: "Payout Booster +10%",
        subtitle: "Applies a one-time payout multiplier.",
        starsCost: 80,
        effectPct: 10,
      },
      {
        id: "seed_product_4",
        category: "PAY_BONUS",
        title: "Payout Booster +20%",
        subtitle: "Use on complex assignments.",
        starsCost: 150,
        effectPct: 20,
      },
    ]);

  await upsertRows(prisma.purchase, [
      {
        id: "seed_purchase_1",
        contractorId: "seed_profile_worker_1",
        productId: "seed_product_3",
        status: "CONSUMED",
        consumedAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
        appliedToAssignmentId: "seed_assignment_1",
      },
      {
        id: "seed_purchase_2",
        contractorId: "seed_profile_worker_2",
        productId: "seed_product_1",
        status: "ACTIVE",
        expiresAt: new Date(now.getTime() + 20 * 24 * 60 * 60 * 1000),
        appliedToAssignmentId: "seed_assignment_2",
      },
      {
        id: "seed_purchase_3",
        contractorId: "seed_profile_worker_3",
        productId: "seed_product_4",
        status: "EXPIRED",
        expiresAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
        appliedToAssignmentId: "seed_assignment_3",
      },
      {
        id: "seed_purchase_4",
        contractorId: "seed_profile_manager_1",
        productId: "seed_product_2",
        status: "ACTIVE",
        expiresAt: new Date(now.getTime() + 25 * 24 * 60 * 60 * 1000),
      },
    ]);

  await upsertRows(prisma.gigReview, [
      {
        id: "seed_review_1",
        assignmentId: "seed_assignment_1",
        reviewerMemberId: "seed_member_2",
        starsRating: 5,
        comment: "Accurate count and clean handoff.",
        decision: "APPROVED",
      },
      {
        id: "seed_review_2",
        assignmentId: "seed_assignment_2",
        reviewerMemberId: "seed_member_6",
        starsRating: 5,
        comment: "On-time delivery and complete proof photos.",
        decision: "APPROVED",
      },
      {
        id: "seed_review_3",
        assignmentId: "seed_assignment_3",
        reviewerMemberId: "seed_member_9",
        starsRating: 4,
        comment: "Minor edits needed, but accepted.",
        decision: "APPROVED",
      },
      {
        id: "seed_review_4",
        assignmentId: "seed_assignment_4",
        reviewerMemberId: "seed_member_12",
        starsRating: 3,
        comment: "Missing final signage photo. Resubmit required.",
        decision: "REJECTED",
      },
    ]);

  await upsertRows(prisma.starsTransaction, [
      {
        id: "seed_stars_tx_1",
        contractorId: "seed_profile_worker_1",
        delta: 13,
        reason: "EARNED_FROM_REVIEW",
        gigId: "seed_gig_2",
        assignmentId: "seed_assignment_1",
      },
      {
        id: "seed_stars_tx_2",
        contractorId: "seed_profile_worker_2",
        delta: 16,
        reason: "EARNED_FROM_REVIEW",
        gigId: "seed_gig_3",
        assignmentId: "seed_assignment_2",
      },
      {
        id: "seed_stars_tx_3",
        contractorId: "seed_profile_worker_3",
        delta: -150,
        reason: "SPENT_ON_PRODUCT",
        purchaseId: "seed_purchase_3",
        assignmentId: "seed_assignment_3",
      },
      {
        id: "seed_stars_tx_4",
        contractorId: "seed_profile_worker_1",
        delta: -80,
        reason: "SPENT_ON_PRODUCT",
        purchaseId: "seed_purchase_1",
        assignmentId: "seed_assignment_1",
      },
    ]);

  await upsertRows(prisma.moneyTransaction, [
      {
        id: "seed_money_tx_1",
        contractorId: "seed_profile_worker_1",
        amountCents: 9200,
        reason: "PAYOUT",
        gigId: "seed_gig_2",
        assignmentId: "seed_assignment_1",
      },
      {
        id: "seed_money_tx_2",
        contractorId: "seed_profile_worker_2",
        amountCents: 11500,
        reason: "PAYOUT",
        gigId: "seed_gig_3",
        assignmentId: "seed_assignment_2",
      },
      {
        id: "seed_money_tx_3",
        contractorId: "seed_profile_worker_3",
        amountCents: 13200,
        reason: "PAYOUT",
        gigId: "seed_gig_4",
        assignmentId: "seed_assignment_3",
      },
      {
        id: "seed_money_tx_4",
        contractorId: "seed_profile_worker_1",
        amountCents: -1200,
        reason: "ADJUSTMENT",
        gigId: "seed_gig_5",
        assignmentId: "seed_assignment_4",
      },
    ]);

  console.log("Seed complete.");
  console.log("Login email examples: admin@qlaim.dev, worker1@qlaim.dev");
  console.log("Shared password for all seed users: Password123!");
}

main()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
