-- AlterTable
ALTER TABLE "Gig"
ADD COLUMN "bumpEverySeconds" INTEGER NOT NULL DEFAULT 1800,
ADD COLUMN "bumpCents" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "maxBumps" INTEGER,
ADD COLUMN "maxPriceCents" INTEGER,
ADD COLUMN "baseStars" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "starsBumpEverySeconds" INTEGER NOT NULL DEFAULT 1800,
ADD COLUMN "starsBumpAmount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "maxAgeBonusStars" INTEGER,
ADD COLUMN "repostBonusPerRepost" INTEGER NOT NULL DEFAULT 1;
